function Request-CertificateViaCertreq {
    <#
    .SYNOPSIS
    Submits a certificate signing request (CSR) to a Windows Certificate Authority using certreq.exe.

    .DESCRIPTION
    This function submits a CSR file to a specified Certificate Authority using certreq.exe and a provided certificate template.
    If the request is placed in a pending state, a JSON file is written to the output directory to track the request ID and metadata.

    .PARAMETER CsrPath
    Full path to the .csr file to submit.

    .PARAMETER CAConfig
    The Certificate Authority configuration string, e.g., 'CA01\My-CA'.

    .PARAMETER CertTemplate
    The certificate template name to use, e.g., 'WebServer'.

    .PARAMETER OutputDirectory
    Output path where the issued certificate and tracking JSON will be saved.

    .PARAMETER CertOutputFile
    Optional custom name or path for the issued certificate (.cer).

    .EXAMPLE
    Request-CertificateViaCertreq -CsrPath 'C:\Certs\web01.csr' -CAConfig 'CA01\RootCA' -CertTemplate 'WebServer'

    .EXAMPLE
    Request-CertificateViaCertreq -CsrPath 'C:\Certs\web01.csr' -CAConfig 'CA01\RootCA' -CertTemplate 'WebServer' -CertOutputFile 'web01-issued.cer'
    #>

    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [string]$CsrPath,

        [Parameter(Mandatory = $true)]
        [string]$CAConfig,

        [Parameter(Mandatory = $true)]
        [string]$CertTemplate,

        [string]$OutputDirectory = (Split-Path -Path $CsrPath),
        [string]$CertOutputFile = $null
    )

    if (-not (Test-Path $CsrPath)) {
        throw "❌ CSR file not found: $CsrPath"
    }

    $baseName = [IO.Path]::GetFileNameWithoutExtension($CsrPath)

    if ([string]::IsNullOrWhiteSpace($CertOutputFile)) {
        $certOutput = Join-Path $OutputDirectory "$baseName.cer"
    } elseif ([IO.Path]::IsPathRooted($CertOutputFile)) {
        $certOutput = $CertOutputFile
    } else {
        $certOutput = Join-Path $OutputDirectory $CertOutputFile
    }

    $attribString = "CertificateTemplate:$CertTemplate"

    $certreqOutput = certreq.exe -submit -config $CAConfig -attrib $attribString $CsrPath $certOutput 2>&1

    Write-Host "📤 certreq output:"
    $certreqOutput | ForEach-Object { Write-Host "  $_" }

    $requestId = $null
    foreach ($line in $certreqOutput) {
        if ($line -match '(RequestId|Anforderungs-ID):\s*"?(\d+)"?') {
            $requestId = $Matches[2]
            break
        }
    }

    if ($null -ne $requestId) {
        Write-Host "⌛ Request is pending approval, RequestId: $requestId"

        $trackingInfo = @{
            RequestId       = $requestId
            CommonName      = $baseName
            CsrPath         = $CsrPath
            CAConfig        = $CAConfig
            CertTemplate    = $CertTemplate
            Timestamp       = (Get-Date).ToString('s')
            CertOutputPath  = $certOutput
        }

        $jsonPath = Join-Path $OutputDirectory "$baseName.request.json"
        $trackingInfo | ConvertTo-Json -Depth 3 | Set-Content -Path $jsonPath -Encoding UTF8

        Write-Host "📝 Request tracking file written: $jsonPath"
        return $jsonPath
    } elseif (Test-Path $certOutput) {
        Write-Host "✅ Certificate issued: $certOutput"
        return $certOutput
    } else {
        throw "❌ Certificate request failed or returned unknown status."
    }
}
# SIG # Begin signature block
# MIIrcwYJKoZIhvcNAQcCoIIrZDCCK2ACAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUq6C+DcjBNfkJecfifX1nsTVt
# STyggiT/MIIFjTCCBHWgAwIBAgIQDpsYjvnQLefv21DiCEAYWjANBgkqhkiG9w0B
# AQwFADBlMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYD
# VQQLExB3d3cuZGlnaWNlcnQuY29tMSQwIgYDVQQDExtEaWdpQ2VydCBBc3N1cmVk
# IElEIFJvb3QgQ0EwHhcNMjIwODAxMDAwMDAwWhcNMzExMTA5MjM1OTU5WjBiMQsw
# CQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3d3cu
# ZGlnaWNlcnQuY29tMSEwHwYDVQQDExhEaWdpQ2VydCBUcnVzdGVkIFJvb3QgRzQw
# ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC/5pBzaN675F1KPDAiMGkz
# 7MKnJS7JIT3yithZwuEppz1Yq3aaza57G4QNxDAf8xukOBbrVsaXbR2rsnnyyhHS
# 5F/WBTxSD1Ifxp4VpX6+n6lXFllVcq9ok3DCsrp1mWpzMpTREEQQLt+C8weE5nQ7
# bXHiLQwb7iDVySAdYyktzuxeTsiT+CFhmzTrBcZe7FsavOvJz82sNEBfsXpm7nfI
# SKhmV1efVFiODCu3T6cw2Vbuyntd463JT17lNecxy9qTXtyOj4DatpGYQJB5w3jH
# trHEtWoYOAMQjdjUN6QuBX2I9YI+EJFwq1WCQTLX2wRzKm6RAXwhTNS8rhsDdV14
# Ztk6MUSaM0C/CNdaSaTC5qmgZ92kJ7yhTzm1EVgX9yRcRo9k98FpiHaYdj1ZXUJ2
# h4mXaXpI8OCiEhtmmnTK3kse5w5jrubU75KSOp493ADkRSWJtppEGSt+wJS00mFt
# 6zPZxd9LBADMfRyVw4/3IbKyEbe7f/LVjHAsQWCqsWMYRJUadmJ+9oCw++hkpjPR
# iQfhvbfmQ6QYuKZ3AeEPlAwhHbJUKSWJbOUOUlFHdL4mrLZBdd56rF+NP8m800ER
# ElvlEFDrMcXKchYiCd98THU/Y+whX8QgUWtvsauGi0/C1kVfnSD8oR7FwI+isX4K
# Jpn15GkvmB0t9dmpsh3lGwIDAQABo4IBOjCCATYwDwYDVR0TAQH/BAUwAwEB/zAd
# BgNVHQ4EFgQU7NfjgtJxXWRM3y5nP+e6mK4cD08wHwYDVR0jBBgwFoAUReuir/SS
# y4IxLVGLp6chnfNtyA8wDgYDVR0PAQH/BAQDAgGGMHkGCCsGAQUFBwEBBG0wazAk
# BggrBgEFBQcwAYYYaHR0cDovL29jc3AuZGlnaWNlcnQuY29tMEMGCCsGAQUFBzAC
# hjdodHRwOi8vY2FjZXJ0cy5kaWdpY2VydC5jb20vRGlnaUNlcnRBc3N1cmVkSURS
# b290Q0EuY3J0MEUGA1UdHwQ+MDwwOqA4oDaGNGh0dHA6Ly9jcmwzLmRpZ2ljZXJ0
# LmNvbS9EaWdpQ2VydEFzc3VyZWRJRFJvb3RDQS5jcmwwEQYDVR0gBAowCDAGBgRV
# HSAAMA0GCSqGSIb3DQEBDAUAA4IBAQBwoL9DXFXnOF+go3QbPbYW1/e/Vwe9mqyh
# hyzshV6pGrsi+IcaaVQi7aSId229GhT0E0p6Ly23OO/0/4C5+KH38nLeJLxSA8hO
# 0Cre+i1Wz/n096wwepqLsl7Uz9FDRJtDIeuWcqFItJnLnU+nBgMTdydE1Od/6Fmo
# 8L8vC6bp8jQ87PcDx4eo0kxAGTVGamlUsLihVo7spNU96LHc/RzY9HdaXFSMb++h
# UD38dglohJ9vytsgjTVgHAIDyyCwrFigDkBjxZgiwbJZ9VVrzyerbHbObyMt9H5x
# aiNrIv8SuFQtJ37YOtnwtoeW/VvRXKwYw02fc7cBqZ9Xql4o4rmUMIIGrjCCBJag
# AwIBAgIQBzY3tyRUfNhHrP0oZipeWzANBgkqhkiG9w0BAQsFADBiMQswCQYDVQQG
# EwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3d3cuZGlnaWNl
# cnQuY29tMSEwHwYDVQQDExhEaWdpQ2VydCBUcnVzdGVkIFJvb3QgRzQwHhcNMjIw
# MzIzMDAwMDAwWhcNMzcwMzIyMjM1OTU5WjBjMQswCQYDVQQGEwJVUzEXMBUGA1UE
# ChMORGlnaUNlcnQsIEluYy4xOzA5BgNVBAMTMkRpZ2lDZXJ0IFRydXN0ZWQgRzQg
# UlNBNDA5NiBTSEEyNTYgVGltZVN0YW1waW5nIENBMIICIjANBgkqhkiG9w0BAQEF
# AAOCAg8AMIICCgKCAgEAxoY1BkmzwT1ySVFVxyUDxPKRN6mXUaHW0oPRnkyibaCw
# zIP5WvYRoUQVQl+kiPNo+n3znIkLf50fng8zH1ATCyZzlm34V6gCff1DtITaEfFz
# sbPuK4CEiiIY3+vaPcQXf6sZKz5C3GeO6lE98NZW1OcoLevTsbV15x8GZY2UKdPZ
# 7Gnf2ZCHRgB720RBidx8ald68Dd5n12sy+iEZLRS8nZH92GDGd1ftFQLIWhuNyG7
# QKxfst5Kfc71ORJn7w6lY2zkpsUdzTYNXNXmG6jBZHRAp8ByxbpOH7G1WE15/teP
# c5OsLDnipUjW8LAxE6lXKZYnLvWHpo9OdhVVJnCYJn+gGkcgQ+NDY4B7dW4nJZCY
# OjgRs/b2nuY7W+yB3iIU2YIqx5K/oN7jPqJz+ucfWmyU8lKVEStYdEAoq3NDzt9K
# oRxrOMUp88qqlnNCaJ+2RrOdOqPVA+C/8KI8ykLcGEh/FDTP0kyr75s9/g64ZCr6
# dSgkQe1CvwWcZklSUPRR8zZJTYsg0ixXNXkrqPNFYLwjjVj33GHek/45wPmyMKVM
# 1+mYSlg+0wOI/rOP015LdhJRk8mMDDtbiiKowSYI+RQQEgN9XyO7ZONj4KbhPvbC
# dLI/Hgl27KtdRnXiYKNYCQEoAA6EVO7O6V3IXjASvUaetdN2udIOa5kM0jO0zbEC
# AwEAAaOCAV0wggFZMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFLoW2W1N
# hS9zKXaaL3WMaiCPnshvMB8GA1UdIwQYMBaAFOzX44LScV1kTN8uZz/nupiuHA9P
# MA4GA1UdDwEB/wQEAwIBhjATBgNVHSUEDDAKBggrBgEFBQcDCDB3BggrBgEFBQcB
# AQRrMGkwJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBBBggr
# BgEFBQcwAoY1aHR0cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0VHJ1
# c3RlZFJvb3RHNC5jcnQwQwYDVR0fBDwwOjA4oDagNIYyaHR0cDovL2NybDMuZGln
# aWNlcnQuY29tL0RpZ2lDZXJ0VHJ1c3RlZFJvb3RHNC5jcmwwIAYDVR0gBBkwFzAI
# BgZngQwBBAIwCwYJYIZIAYb9bAcBMA0GCSqGSIb3DQEBCwUAA4ICAQB9WY7Ak7Zv
# mKlEIgF+ZtbYIULhsBguEE0TzzBTzr8Y+8dQXeJLKftwig2qKWn8acHPHQfpPmDI
# 2AvlXFvXbYf6hCAlNDFnzbYSlm/EUExiHQwIgqgWvalWzxVzjQEiJc6VaT9Hd/ty
# dBTX/6tPiix6q4XNQ1/tYLaqT5Fmniye4Iqs5f2MvGQmh2ySvZ180HAKfO+ovHVP
# ulr3qRCyXen/KFSJ8NWKcXZl2szwcqMj+sAngkSumScbqyQeJsG33irr9p6xeZmB
# o1aGqwpFyd/EjaDnmPv7pp1yr8THwcFqcdnGE4AJxLafzYeHJLtPo0m5d2aR8XKc
# 6UsCUqc3fpNTrDsdCEkPlM05et3/JWOZJyw9P2un8WbDQc1PtkCbISFA0LcTJM3c
# HXg65J6t5TRxktcma+Q4c6umAU+9Pzt4rUyt+8SVe+0KXzM5h0F4ejjpnOHdI/0d
# KNPH+ejxmF/7K9h+8kaddSweJywm228Vex4Ziza4k9Tm8heZWcpw8De/mADfIBZP
# J/tgZxahZrrdVcA6KYawmKAr7ZVBtzrVFZgxtGIJDwq9gdkT/r+k0fNX2bwE+oLe
# Mt8EifAAzV3C+dAjfwAL5HYCJtnwZXZCpimHCUcr5n8apIUP/JiW9lVUKx+A+sDy
# Divl1vupL0QVSucTDh3bNzgaoSv27dZ8/DCCBrwwggSkoAMCAQICEAuuZrxaun+V
# h8b56QTjMwQwDQYJKoZIhvcNAQELBQAwYzELMAkGA1UEBhMCVVMxFzAVBgNVBAoT
# DkRpZ2lDZXJ0LCBJbmMuMTswOQYDVQQDEzJEaWdpQ2VydCBUcnVzdGVkIEc0IFJT
# QTQwOTYgU0hBMjU2IFRpbWVTdGFtcGluZyBDQTAeFw0yNDA5MjYwMDAwMDBaFw0z
# NTExMjUyMzU5NTlaMEIxCzAJBgNVBAYTAlVTMREwDwYDVQQKEwhEaWdpQ2VydDEg
# MB4GA1UEAxMXRGlnaUNlcnQgVGltZXN0YW1wIDIwMjQwggIiMA0GCSqGSIb3DQEB
# AQUAA4ICDwAwggIKAoICAQC+anOf9pUhq5Ywultt5lmjtej9kR8YxIg7apnjpcH9
# CjAgQxK+CMR0Rne/i+utMeV5bUlYYSuuM4vQngvQepVHVzNLO9RDnEXvPghCaft0
# djvKKO+hDu6ObS7rJcXa/UKvNminKQPTv/1+kBPgHGlP28mgmoCw/xi6FG9+Un1h
# 4eN6zh926SxMe6We2r1Z6VFZj75MU/HNmtsgtFjKfITLutLWUdAoWle+jYZ49+wx
# GE1/UXjWfISDmHuI5e/6+NfQrxGFSKx+rDdNMsePW6FLrphfYtk/FLihp/feun0e
# V+pIF496OVh4R1TvjQYpAztJpVIfdNsEvxHofBf1BWkadc+Up0Th8EifkEEWdX4r
# A/FE1Q0rqViTbLVZIqi6viEk3RIySho1XyHLIAOJfXG5PEppc3XYeBH7xa6VTZ3r
# OHNeiYnY+V4j1XbJ+Z9dI8ZhqcaDHOoj5KGg4YuiYx3eYm33aebsyF6eD9MF5IDb
# PgjvwmnAalNEeJPvIeoGJXaeBQjIK13SlnzODdLtuThALhGtyconcVuPI8AaiCai
# JnfdzUcb3dWnqUnjXkRFwLtsVAxFvGqsxUA2Jq/WTjbnNjIUzIs3ITVC6VBKAOlb
# 2u29Vwgfta8b2ypi6n2PzP0nVepsFk8nlcuWfyZLzBaZ0MucEdeBiXL+nUOGhCjl
# +QIDAQABo4IBizCCAYcwDgYDVR0PAQH/BAQDAgeAMAwGA1UdEwEB/wQCMAAwFgYD
# VR0lAQH/BAwwCgYIKwYBBQUHAwgwIAYDVR0gBBkwFzAIBgZngQwBBAIwCwYJYIZI
# AYb9bAcBMB8GA1UdIwQYMBaAFLoW2W1NhS9zKXaaL3WMaiCPnshvMB0GA1UdDgQW
# BBSfVywDdw4oFZBmpWNe7k+SH3agWzBaBgNVHR8EUzBRME+gTaBLhklodHRwOi8v
# Y3JsMy5kaWdpY2VydC5jb20vRGlnaUNlcnRUcnVzdGVkRzRSU0E0MDk2U0hBMjU2
# VGltZVN0YW1waW5nQ0EuY3JsMIGQBggrBgEFBQcBAQSBgzCBgDAkBggrBgEFBQcw
# AYYYaHR0cDovL29jc3AuZGlnaWNlcnQuY29tMFgGCCsGAQUFBzAChkxodHRwOi8v
# Y2FjZXJ0cy5kaWdpY2VydC5jb20vRGlnaUNlcnRUcnVzdGVkRzRSU0E0MDk2U0hB
# MjU2VGltZVN0YW1waW5nQ0EuY3J0MA0GCSqGSIb3DQEBCwUAA4ICAQA9rR4fdplb
# 4ziEEkfZQ5H2EdubTggd0ShPz9Pce4FLJl6reNKLkZd5Y/vEIqFWKt4oKcKz7wZm
# Xa5VgW9B76k9NJxUl4JlKwyjUkKhk3aYx7D8vi2mpU1tKlY71AYXB8wTLrQeh83p
# XnWwwsxc1Mt+FWqz57yFq6laICtKjPICYYf/qgxACHTvypGHrC8k1TqCeHk6u4I/
# VBQC9VK7iSpU5wlWjNlHlFFv/M93748YTeoXU/fFa9hWJQkuzG2+B7+bMDvmgF8V
# lJt1qQcl7YFUMYgZU1WM6nyw23vT6QSgwX5Pq2m0xQ2V6FJHu8z4LXe/371k5QrN
# 9FQBhLLISZi2yemW0P8ZZfx4zvSWzVXpAb9k4Hpvpi6bUe8iK6WonUSV6yPlMwer
# wJZP/Gtbu3CKldMnn+LmmRTkTXpFIEB06nXZrDwhCGED+8RsWQSIXZpuG4WLFQOh
# tloDRWGoCwwc6ZpPddOFkM2LlTbMcqFSzm4cd0boGhBq7vkqI1uHRz6Fq1IX7TaR
# QuR+0BGOzISkcqwXu7nMpFu3mgrlgbAW+BzikRVQ3K2YHcGkiKjA4gi4OA/kz1YC
# sdhIBHXqBzR0/Zd2QwQ/l4Gxftt/8wY3grcc/nS//TVkej9nmUYu83BDtccHHXKi
# bMs/yXHhDXNkoPIdynhVAku7aRZOwqw6pDCCB38wggVnoAMCAQICE1kAAAFgY9B3
# m6yaV+MAAAAAAWAwDQYJKoZIhvcNAQELBQAwgf8xCzAJBgNVBAYTAkFUMRUwEwYD
# VQQIEwxMb3dlckF1c3RyaWExFzAVBgNVBAcTDktsb3N0ZXJuZXVidXJnMRUwEwYD
# VQQKEwxEaWVNb21wZmRpZXMxIDAeBgNVBAsTF0ZvciBhdXRob3JpemVkIHVzZSBv
# bmx5MSgwJgYDVQQLEx9DZXJ0aWZpY2F0aW9uIFNlcnZpY2VzIERpdmlzaW9uMTgw
# NgYDVQQDEy9EaWUgTW9tcGZkaWVzIFN1Ym9yZGluYXRlIENlcnRpZmljYXRlIEF1
# dGhvcml0eTEjMCEGCSqGSIb3DQEJARYUcGtpQGRpZS1tb21wZmRpZXMuYXQwHhcN
# MjUwNDI4MTk1OTU3WhcNMjYwNDI4MTk1OTU3WjCBsDEVMBMGCgmSJomT8ixkARkW
# BWxvY2FsMRgwFgYKCZImiZPyLGQBGRYIbW9tcGZkaWUxFTATBgNVBAsTDERpZU1v
# bXBmZGllczEOMAwGA1UECxMFVGllcjIxEDAOBgNVBAsTB1QyLVVzZXIxGjAYBgNV
# BAMMEVJhaW11bmQgUGxpZcOfbmlnMSgwJgYJKoZIhvcNAQkBFhltb21wZmRpZUBk
# aWUtbW9tcGZkaWVzLmF0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
# uuMsIx4lDbNaz9JEQak3V1l7bVEiVpF2eZVgmG4QXQOz6PULEsK7SO99yBGTfJWl
# UT2JVC9Q2+23+SrmqTmtRrionBcjSJAdxWhoSziUFIjibhzvGGZYdngEeVTZlMEy
# jFFSiesXodMLsdPEBqbjuhRqcMN64DkxL2u92rcygBLntoXYZDYuRgYot4s/dfNx
# pTnf/v6wnhb482W4MWyjkJP/dMm0i55qQ0g2q0mxWMJ4OIi9R+viJBayXLeIi8gT
# rexplUMsCd2J3duCpVH2mSybv+45bWudiB7QmU7G/iD9IQsttQpE2k9eTDiLMRu4
# TH1avy+K+GptJ5uPzb7VKQIDAQABo4ICPzCCAjswPAYJKwYBBAGCNxUHBC8wLQYl
# KwYBBAGCNxUIgYaOU97sCYXlhTuCk8Bahd/zKoEk7Phih4CsQwIBZAIBAjATBgNV
# HSUEDDAKBggrBgEFBQcDAzAOBgNVHQ8BAf8EBAMCB4AwGwYJKwYBBAGCNxUKBA4w
# DDAKBggrBgEFBQcDAzBOBgkrBgEEAYI3GQIEQTA/oD0GCisGAQQBgjcZAgGgLwQt
# Uy0xLTUtMjEtMjIwNjMwNzI1OS05OTMxNjA4NzktMTQ5MzY4OTk1My0xMTA1MDQG
# A1UdEQQtMCugKQYKKwYBBAGCNxQCA6AbDBlNb21wZmRpZUBkaWUtbW9tcGZkaWVz
# LmF0MB0GA1UdDgQWBBQngRlGy3qcgp1sbY9kkKFppOmnwjAfBgNVHSMEGDAWgBRj
# OoI2iSCN4NWsgu40a7Ulr8KNVDBzBgNVHR8EbDBqMGigZqBkhmJodHRwOi8vcGtp
# LmRpZS1tb21wZmRpZXMuYXQvQ2VydEVucm9sbC9EaWUlMjBNb21wZmRpZXMlMjBT
# dWJvcmRpbmF0ZSUyMENlcnRpZmljYXRlJTIwQXV0aG9yaXR5LmNybDB+BggrBgEF
# BQcBAQRyMHAwbgYIKwYBBQUHMAKGYmh0dHA6Ly9wa2kuZGllLW1vbXBmZGllcy5h
# dC9DZXJ0RW5yb2xsL0RpZSUyME1vbXBmZGllcyUyMFN1Ym9yZGluYXRlJTIwQ2Vy
# dGlmaWNhdGUlMjBBdXRob3JpdHkuY3J0MA0GCSqGSIb3DQEBCwUAA4ICAQAzj5n3
# XBfpx5zOpQpFFlwFgN05N1Na4Gl33ZzGpzAYkDYieGsrbNRHIxePcqE0X2BpF369
# 1OvyyLDqd5QD/j7Y8VX/frPP8LuNMmBrv/LgYdlNeXcCP8ljt37jDgdESLIi9a5N
# PBUtbIVXqBjJzqqIQ5TQNrwrjelL1HpV8ybmR5/TBX1ArQ98E9JtEV0wugevftAp
# 40TC9t+4EUwqCD86yyJpYSTaTqc4eC2gvajtov5qFs0+fZBGHNReL4GuEP8Hn3NE
# 2AKrLes4pftdJM8cjggp4vzTfzKzOyEChMprMlDXRtVTpNVGFC4rU8+Oz7BTx+6u
# uz3Pgf831hI8hoj+UbQtHfRzjY0+b27relvraMvUtgGxvoYxaly151B4eYIE1c77
# /Oc7MZ0s0e7UwLgDO8gJEQDS7E/jwJdcUddfl+fHxckMPNF0LxU3IhQQxS+evz76
# 9X+7WYX0PPhqbJSBnx1EENNxS4s5x2t2c6R8AbiUPNKol2mZlIPes0ZBi2jcgQ4d
# 8miS9zsz5a90qCEzJpyhcG9vxdQVKQx0cPXsrNkCiQ2+2DXy459XGvS1crdOkyRj
# Hp4Sea3I6gWaXEbd4DG9Zcu/5Je5PPu60pghu9fdRitdjui0jKVQjstlSZtoX6QP
# eLlAqlPVndncusGobTmcUd2bPuj9nwP/w77uRDCCCnUwgghdoAMCAQICE2oAAAAE
# LA49J5ScAx8AAAAAAAQwDQYJKoZIhvcNAQELBQAwgfgxIzAhBgkqhkiG9w0BCQEW
# FHBraUBkaWUtbW9tcGZkaWVzLmF0MQswCQYDVQQGEwJBVDEVMBMGA1UECBMMTG93
# ZXJBdXN0cmlhMRcwFQYDVQQHEw5LbG9zdGVybmV1YnVyZzEVMBMGA1UEChMMRGll
# TW9tcGZkaWVzMSAwHgYDVQQLExdGb3IgYXV0aG9yaXplZCB1c2Ugb25seTEoMCYG
# A1UECxMfQ2VydGlmaWNhdGlvbiBTZXJ2aWNlcyBEaXZpc2lvbjExMC8GA1UEAxMo
# RGllIE1vbXBmZGllcyBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yMDAy
# MjMxMzQxNDlaFw0zMDAyMjMxMzUxNDlaMIH/MQswCQYDVQQGEwJBVDEVMBMGA1UE
# CBMMTG93ZXJBdXN0cmlhMRcwFQYDVQQHEw5LbG9zdGVybmV1YnVyZzEVMBMGA1UE
# ChMMRGllTW9tcGZkaWVzMSAwHgYDVQQLExdGb3IgYXV0aG9yaXplZCB1c2Ugb25s
# eTEoMCYGA1UECxMfQ2VydGlmaWNhdGlvbiBTZXJ2aWNlcyBEaXZpc2lvbjE4MDYG
# A1UEAxMvRGllIE1vbXBmZGllcyBTdWJvcmRpbmF0ZSBDZXJ0aWZpY2F0ZSBBdXRo
# b3JpdHkxIzAhBgkqhkiG9w0BCQEWFHBraUBkaWUtbW9tcGZkaWVzLmF0MIICIjAN
# BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA5jBry0q/1zH5VNOt8L/IbIemAlCc
# nf7tDpxERd7pVrWV0OGSpD7FIL8RxGiN/bmKi7gEh1cxPC7Be6bgsZOfVuDE04kt
# QzF6IaUFoiUorRb1B5fL0O7Phr4xBPh79AiV8Qui2Umax9pHUg1eIve1U21bnq/6
# 3pxkHYZMV3noGUxJclfAKQo6eM4WpK7LFGZ4JL1ngZGgW75brkuJ6JKEl3GmlM1V
# vuaYhgGjB785KYb2E19iW/gjpzNjnlhdy5e8u9YBJ4iAE8xLUVRR4B6m41uQAr2R
# d9ukAfJeVbBd5Fx4RboNvCbAoZt3fRq7RYPUGd1QxvZhANauI2JGmPeflXvqFVfX
# NMt7RMtNYo9nWQ02YUFWHnZpOvmIofN0gZEi4IckgtCr7iHEYMiN54Ah4okC3fk2
# 9ip7QJMkJrxbqEKsRzBerHnuICAQl2Yp/s7cfIGUYX5e1AQ+2Tdnr1c1H+SdD2vo
# SSBYL5LpMv85RD6JfvZAKHeL47/dKmapvOU3EavJiAdkBjF1j8I1heqD37S2BKEP
# FCcf1JOOG0RDT54huUdFYMmQ3LD4GZZ1+tPhywB9S7TD2CSkkzs+6EtUJjjljgPU
# GL4ZxMPBABwfIiwhdYi1A/n4ES+9Ko2CWOP8JKXFoT68i9njFoKVEbmFYVq+4/fl
# zZUUGntQKiMcbJ0CAwEAAaOCA+0wggPpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1Ud
# DgQWBBRjOoI2iSCN4NWsgu40a7Ulr8KNVDCCAnAGA1UdIASCAmcwggJjMIICXwYI
# KwYBBAGDrmwwggJRMIICBgYIKwYBBQUHAgIwggH4HoIB9ABUAGgAaQBzACAARQBu
# AHQAZQByAHAAcgBpAHMAZQAgAEMAZQByAHQAaQBmAGkAYwBhAHQAaQBvAG4AIABB
# AHUAdABoAG8AcgBpAHQAeQAgAGkAcwAgAGEAbgAgAGkAbgB0AGUAcgBuAGEAbAAg
# AHIAZQBzAG8AdQByAGMAZQAuACAAIABDAGUAcgB0AGkAZgBpAGMAYQB0AGUAcwAg
# AGkAcwBzAHUAZQBkACAAYgB5ACAAdABoAGkAcwAgAEMAQQAgAGEAcgBlACAAZgBv
# AHIAIABpAG4AdABlAHIAbgBhAGwAIAB1AHMAZQAgAG8AbgBsAHkALgAgACAARgBv
# AHIAIABtAG8AcgBlACAAaQBuAGYAbwByAG0AYQB0AGkAbwBuACwAIABwAGwAZQBh
# AHMAZQAgAHIAZQBmAGUAcgAgAHQAbwAgAHQAaABlACAAQwBlAHIAdABpAGYAaQBj
# AGEAdABpAG8AbgAgAFAAcgBhAGMAdABpAGMAZQAgAFMAdABhAHQAZQBtAGUAbgB0
# ACAAYQB0ACAAaAB0AHQAcAA6AC8ALwBwAGsAaQAuAGQAaQBlAC0AbQBvAG0AcABm
# AGQAaQBlAHMALgBhAHQALwBDAGUAcgB0AEUAbgByAG8AbABsAC8AYwBwAHMALgBo
# AHQAbQBsMEUGCCsGAQUFBwIBFjlodHRwOi8vcGtpLmRpZS1tb21wZmRpZXMuYXQv
# Q2VydEVucm9sbC9zdWJMZWdhbFBvbGljeS50eHQwGQYJKwYBBAGCNxQCBAweCgBT
# AHUAYgBDAEEwCwYDVR0PBAQDAgGGMBIGA1UdEwEB/wQIMAYBAf8CAQAwHwYDVR0j
# BBgwFoAUtQCEHja4hhtU3thT5mGViZ3GJF4wbAYDVR0fBGUwYzBhoF+gXYZbaHR0
# cDovL3BraS5kaWUtbW9tcGZkaWVzLmF0L0NlcnRFbnJvbGwvRGllJTIwTW9tcGZk
# aWVzJTIwUm9vdCUyMENlcnRpZmljYXRlJTIwQXV0aG9yaXR5LmNybDB3BggrBgEF
# BQcBAQRrMGkwZwYIKwYBBQUHMAKGW2h0dHA6Ly9wa2kuZGllLW1vbXBmZGllcy5h
# dC9DZXJ0RW5yb2xsL0RpZSUyME1vbXBmZGllcyUyMFJvb3QlMjBDZXJ0aWZpY2F0
# ZSUyMEF1dGhvcml0eS5jcnQwDQYJKoZIhvcNAQELBQADggIBAKg8cPpnjzLmbh1Z
# innzwb7ro5HxzeYss9tO4NZJcHOSOc8vHLtCpQNhbaLj3t1wN4UJtY9SYx8PdGdm
# z2OvjqxCHlab6GXaFB2zVLBvF4HL9GXFoa2WaD1/sjJihzbSWLZ5armx7siq0rAZ
# QfN0/cWqxoMnpCCWKhUOkBlgpZXjIjaMJAhE7kDomLbTzq7T1PgQp6PiJn0iLVxn
# aQYRQEGH2jOIBr8IOq7XiFIquoFlJbpr4VeNEIMxmUqaptHX+EEZW3APDQ0ab5si
# P+eFnExi016Ijjmd/IyUviH0Kvqiua0Y1WAStWQUXeIgoOGCPVNLk+UJwcW9tWD8
# hWCFT9f5cN9iXX3x/pgUdZlgFaSXmtqRfvxbwl0a20K0yZoM8YKAAWFrNe2ZbUNU
# XVouxt+UdXGSrGxi4p+QQGUoQa/KeszAP05CKU3aTUj2JlyaFkVSWXabMChaw8tf
# fvf3/a0OJTqb41Qic7iEpklhWSUD1rZwniYNlMAiwFE82Yhv9Lmu/+I7FdhJJO/C
# DVN4P3HVihE2ZmvrzA5MferPlOo6E8GSDIbeAGuZm7UJ8Apz4vxJ/JLHooRmdGv8
# hkP30zRDqGyWMPFxfuMMCpj8tPBRiq0LoSKs5k6gLUHuHrpJuWWwWeA91BesLTKU
# pdgnd2cRje2dHImzGnIXT4DZBZ2FMYIF3jCCBdoCAQEwggEXMIH/MQswCQYDVQQG
# EwJBVDEVMBMGA1UECBMMTG93ZXJBdXN0cmlhMRcwFQYDVQQHEw5LbG9zdGVybmV1
# YnVyZzEVMBMGA1UEChMMRGllTW9tcGZkaWVzMSAwHgYDVQQLExdGb3IgYXV0aG9y
# aXplZCB1c2Ugb25seTEoMCYGA1UECxMfQ2VydGlmaWNhdGlvbiBTZXJ2aWNlcyBE
# aXZpc2lvbjE4MDYGA1UEAxMvRGllIE1vbXBmZGllcyBTdWJvcmRpbmF0ZSBDZXJ0
# aWZpY2F0ZSBBdXRob3JpdHkxIzAhBgkqhkiG9w0BCQEWFHBraUBkaWUtbW9tcGZk
# aWVzLmF0AhNZAAABYGPQd5usmlfjAAAAAAFgMAkGBSsOAwIaBQCgeDAYBgorBgEE
# AYI3AgEMMQowCKACgAChAoAAMBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwG
# CisGAQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMCMGCSqGSIb3DQEJBDEWBBRyFk0N
# cyv7Sk7uNywaKsgwj/vVZTANBgkqhkiG9w0BAQEFAASCAQAt4icm1/drRaN9doss
# wRYZMZkKJGvj/AKBxbP6SCDi6eGX97sxpQ1kvXvh91U58LStWTER2VcaGPr5GqWr
# AiRiabFylvH033TxgLyGoV+e/HFC7WlhH/8u/FLfq+b4BL+URil+wmmzJ27YThBS
# 49T0+QZZj7ODQnKYP6Xrq7ASbisEzYd8bx1gGksAZRmCBtIOMEYdVcPli2yQRktC
# UH27ypPKL+3rYe0Sf3GyniG3+ouiIk+A9rKtCkxHqlqRVAEYI1bvRle/FA97ur4G
# TpSuTdHutejNCgHQEGluehetjA1J7IzUQUB+8/EN6g/BwOlnaf4ZC0puprv3bQiA
# tvP2oYIDIDCCAxwGCSqGSIb3DQEJBjGCAw0wggMJAgEBMHcwYzELMAkGA1UEBhMC
# VVMxFzAVBgNVBAoTDkRpZ2lDZXJ0LCBJbmMuMTswOQYDVQQDEzJEaWdpQ2VydCBU
# cnVzdGVkIEc0IFJTQTQwOTYgU0hBMjU2IFRpbWVTdGFtcGluZyBDQQIQC65mvFq6
# f5WHxvnpBOMzBDANBglghkgBZQMEAgEFAKBpMBgGCSqGSIb3DQEJAzELBgkqhkiG
# 9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTI1MDUxMjE3MjcxNVowLwYJKoZIhvcNAQkE
# MSIEIBS75mS70znmCDb4SAHBQ9os3cGOwLgzraQ/d0MthIV5MA0GCSqGSIb3DQEB
# AQUABIICAD5gqX2eNsMierPe4CegCZ3hpmWb9MFUVZWtlROIaWcdWvHpiQYMpgBY
# V8rV6EFNFGf8lMn/HGucJNcrdN8ibma/Zk14xfYRDOW+WFHj/te0EVlHQqGs0jGD
# T8xua6ftY54gJRbBoNohZ+1BFHVL6Dot4qR5MMej5UHV56hFiw3tXBGADZFknkyT
# Ht/2EYGBxZ9k2fwUauyrbzTckcpsvZV8Xi6z0ZwPQuAf6TfYnEhjSle6VllaguQc
# TXyuEDv8KWyVNbusiRJhB4g6eRD0BmOex5k5MM02VhDx+Rk+qR/JCV7IGoVfTzJQ
# N3D1hif9uwFbBsUZOdJzlEftPsl6StQKpSn5UA0rj254Dr3rKwrC6YfkvzcbYS07
# bZdCBJ2GXxaDKnlBFnmc8tcV8el0+QeJBwtGgpyk2Od2pkj9f9E2KLWeUStx9i6k
# DQjw7UKm0i1gaJaJIf99KmeY6qD3PTt0m9ZDZk3c1XfIevyYAQkm/TA+nn9rrWe3
# KdObDrUQGX2D1gUGaiSsJkTp0Cb6t2Ffl0gHmIgk9CvAp4EdDVQEjmXB9F/UWW+w
# gocT5HqxUrN/qsdZsIwaqNxkwf8CQmXTp1Qw3n/VUWqPPq9hQ6NycMxqXr6Gn+2v
# khL/+TDSfeH4mj9pHmpUPl8up7wivUGr3AiWfE45lfb/PSzrEFbZ
# SIG # End signature block
